apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-04-27T06:51:24Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app.kubernetes.io/instance: test-app
  name: hello-service
  namespace: default
  resourceVersion: "701855"
  uid: 567ba960-f453-46d6-bfa2-5d48db7d7909
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 172.20.142.111
  clusterIPs:
  - 172.20.142.111
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32061
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-ui
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: a567ba960f45346d6bfa25d48db7d790-444939768.ap-southeast-1.elb.amazonaws.com
